"""Scaffolder + template contents (spec §13.2, §13.5, §13.8, §14.2).

A team installs by materializing these files into its repo and answering one
question: ``specs_dir``. That single answer is written into all three places
that consume it (spec §13.5):

1. the caller workflow's ``with: specs_dir:`` inputs,
2. the caller trigger's ``on.push.paths`` filter — GitHub Actions forbids
   variables there, so the *literal* path is written in at scaffold time, and
3. ``CLAUDE.md`` / ``/new-spec`` guidance so generated specs land in the right place.

This module is the single source of truth for the template. ``render_files``
returns the whole tree as (relative_path, content) pairs; ``scaffold`` writes
them. The committed ``template/`` snapshot is just ``render_files`` run with the
default ``specs`` path.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Central product coordinates — where the reusable workflows are published.
DEFAULT_ORG = "growth-beaker"
DEFAULT_REPO = "hureva"
DEFAULT_LIB_REF = "v1"


def _caller_workflow(specs_dir: str, org: str, repo: str, lib_ref: str) -> str:
    return f"""\
# Tenant caller workflow (spec §13.7) — generated by the hureva scaffolder.
# The specs path below is written in literally: GitHub Actions does not allow
# variables in `on.push.paths` (spec §13.5).
name: spec-review

on:
  push:
    branches: ["spec/**"]        # status changes happen on spec branches (§7.4)
    paths: ["{specs_dir}/**"]

jobs:
  gate:
    uses: {org}/{repo}/.github/workflows/status-gate.yml@{lib_ref}
    with:
      specs_dir: {specs_dir}
      # enforced: true            # uncomment to block un-approved specs (§6.3)
    secrets: inherit

  notify:
    uses: {org}/{repo}/.github/workflows/notify.yml@{lib_ref}
    with:
      specs_dir: {specs_dir}
    secrets: inherit
"""


def _roster_yml() -> str:
    return """\
# Central team roster (spec §4.3): the only place channels are defined.
# People are referenced everywhere by their key here (name-only); a name missing
# from this file fails loudly rather than silently. Slack is used if present,
# else email.
people:
  chris:   { email: chris@acme.com, slack: "@chris" }
  elena:   { email: elena@acme.com, slack: "@elena" }
  sam:     { email: sam@acme.com,   slack: "@sam" }
  qa-team: { slack: "#qa" }        # a group is fine; email optional
"""


def _defaults_yml() -> str:
    return """\
# Default review assignment (spec §4.4), copied into a NEW spec's frontmatter at
# creation, then freely overridden per spec. A seed, not a runtime fallback:
# after creation the spec's own frontmatter is the only thing consulted.
owner: chris
approvers: [elena]
commenters: [sam]
viewers: [qa-team]
"""


def _spec_template_md() -> str:
    return """\
---
title: <Feature title>
status: draft            # draft | in_review | approved | implemented | archived
owner: chris             # roster key of the driver
approvers: [elena]       # may sign off; recorded in approved_by
commenters: [sam]        # may comment/suggest, not approve
viewers: [qa-team]       # read-only
approved_by: []          # who has actually signed off (subset of approvers)
approved_at: null        # set when status -> approved
version: "1.0"
# prototype: https://...  # optional clickable prototype link (§11 decision 22)
---

# <Feature title>

## Problem

## Proposed solution

## Open questions
"""


def _claude_md(specs_dir: str) -> str:
    return f"""\
# Working with specs in this repo

This repo uses the **spec review & approval workflow**. When you generate a spec,
follow these rules so it flows through review and the gate unchanged. (This
guidance is tool-neutral — it does not require superpowers.)

## Where specs live

- Specs live under `{specs_dir}/<feature-slug>/spec.md`.
- The team roster is `{specs_dir}/roster.yml`; default roles are
  `{specs_dir}/defaults.yml`.

## How to create a spec

Prefer the one-step command:

```
/new-spec <slug> "Feature title"
```

or run it directly:

```
python -m hureva.new_spec <slug> --title "Feature title" --specs-dir {specs_dir}
```

Either seeds roles from `defaults.yml`, writes `{specs_dir}/<slug>/spec.md`, and
creates a `spec/<slug>` branch. Author by hand from `{specs_dir}/spec.template.md`
if you prefer.

## Frontmatter schema (the runtime contract, §4.2)

```yaml
title: string
status: draft | in_review | approved | implemented | archived
owner: <roster key>
approvers: [<roster key>, ...]   # may sign off
commenters: [<roster key>, ...]  # may comment, not approve
viewers: [<roster key>, ...]     # read-only
approved_by: [<roster key>, ...] # subset of approvers
approved_at: date | null
version: "semver-ish"
```

All people are **roster keys** (names only) — never inline emails or Slack
handles. Seed unset roles from `defaults.yml`; override per spec as needed.

## Lifecycle

`draft -> in_review -> approved -> implemented` (plus `archived`). Pushing a spec
with `status: in_review` onto its `spec/<slug>` branch opens it for review and
notifies the reviewers. Move to `approved` only after the team signs off; the
owner records `approved_by`. Do **not** start the build until `status: approved`.
"""


def _new_spec_command_md(specs_dir: str) -> str:
    return f"""\
---
description: Scaffold a new spec folder, seed roles from defaults.yml, and create its spec/<slug> branch.
argument-hint: <slug> "<Feature title>"
---

Create a new spec for `$ARGUMENTS`.

Run the scaffolder, which reads `{specs_dir}/defaults.yml`, seeds the frontmatter
roles, writes `{specs_dir}/<slug>/spec.md` from the template, and creates a
`spec/<slug>` git branch:

```
python -m hureva.new_spec <slug> --title "<Feature title>" --specs-dir {specs_dir}
```

Then draft the spec body with the user. Leave `status: draft` until they are ready
to open it for review; when they are, set `status: in_review` and push the
`spec/<slug>` branch — that notifies the reviewers.
"""


def render_files(
    specs_dir: str = "specs",
    org: str = DEFAULT_ORG,
    repo: str = DEFAULT_REPO,
    lib_ref: str = DEFAULT_LIB_REF,
) -> dict[str, str]:
    """Return the whole template tree as {relative_path: content}."""
    return {
        f"{specs_dir}/roster.yml": _roster_yml(),
        f"{specs_dir}/defaults.yml": _defaults_yml(),
        f"{specs_dir}/spec.template.md": _spec_template_md(),
        ".github/workflows/spec-review.yml": _caller_workflow(
            specs_dir, org, repo, lib_ref
        ),
        "CLAUDE.md": _claude_md(specs_dir),
        ".claude/commands/new-spec.md": _new_spec_command_md(specs_dir),
    }


def scaffold(
    target_dir: str | Path,
    specs_dir: str = "specs",
    org: str = DEFAULT_ORG,
    repo: str = DEFAULT_REPO,
    lib_ref: str = DEFAULT_LIB_REF,
    force: bool = False,
) -> list[str]:
    """Write the template into ``target_dir``. Returns the paths written.

    Refuses to overwrite existing files unless ``force`` — installing into a repo
    should never clobber a team's real config by accident.
    """
    target = Path(target_dir)
    files = render_files(specs_dir, org, repo, lib_ref)

    if not force:
        clashes = [rel for rel in files if (target / rel).exists()]
        if clashes:
            raise FileExistsError(
                "refusing to overwrite existing files (use --force): "
                + ", ".join(sorted(clashes))
            )

    written: list[str] = []
    for rel, content in files.items():
        dest = target / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content, encoding="utf-8")
        written.append(rel)
    return sorted(written)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="hureva-scaffold", description=__doc__)
    parser.add_argument(
        "--specs-dir",
        default="specs",
        help="root folder for specs (default: specs; e.g. docs/specs)",
    )
    parser.add_argument("--into", default=".", help="target repo directory")
    parser.add_argument("--org", default=DEFAULT_ORG)
    parser.add_argument("--repo", default=DEFAULT_REPO)
    parser.add_argument("--lib-ref", default=DEFAULT_LIB_REF)
    parser.add_argument("--force", action="store_true", help="overwrite existing files")
    args = parser.parse_args(argv)

    written = scaffold(
        target_dir=args.into,
        specs_dir=args.specs_dir,
        org=args.org,
        repo=args.repo,
        lib_ref=args.lib_ref,
        force=args.force,
    )
    print(f"scaffolded {len(written)} files into {args.into} (specs_dir={args.specs_dir}):")
    for rel in written:
        print(f"  {rel}")
    print("\nNext: fill in roster.yml / defaults.yml, add channel secrets, then")
    print("connect your docs tool's git sync (spec §13.3).")
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
